# Generated by Django 5.2.4 on 2025-08-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='perguntas',
            new_name='pesquisas',
        ),
    ]
