# Generated by Django 5.2.4 on 2025-08-04 17:01

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_perguntas_pessoa_pesquisas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(default='')),
                ('perguntas', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pesquisas',
            field=models.JSONField(blank=True, default=data.models.verificar_pesquisas),
        ),
    ]
